NO_PROMO = [
  "Based on the recent promotion cycle evaluations, it became clear that while your project contributions have been invaluable, there's a need to enhance your visibility and influence across the wider organization. Increasing your engagement in cross-departmental initiatives and leading company-wide technical forums could significantly elevate your profile. Let’s identify opportunities for you to lead workshops or present on key projects you’ve driven to a successful outcome. We can also explore mentorship roles within the company to help you build broader networks. I believe by focusing on these areas, we can better position you for future promotional opportunities.",
  "While your technical expertise is exceptional, the feedback highlighted a need for further development in project management and stakeholder communication. Specifically, managing projects with more complex scopes and diverse teams could demonstrate the leadership qualities required for the next level. I suggest we look for upcoming projects that will challenge you in these areas and consider enrolling in a project management course. Additionally, improving direct communication with stakeholders will be crucial. Let’s set some objectives around these skills and review progress regularly.",
  "The decision regarding promotions this cycle pointed to a gap in strategic thinking and decision-making at a higher level. Your technical skills are beyond question, but taking on roles that require strategic planning and execution could demonstrate your capability for larger responsibilities. In the next few months, let’s identify projects where you can play a more strategic role, perhaps as a lead on new initiatives or by contributing to the strategic direction of our technology roadmap. Engaging in these activities could provide the experience needed to prepare for future leadership roles.",
  "Your ability to execute tasks efficiently is commendable. However, the promotion criteria also emphasize team leadership and the ability to inspire and drive the team towards shared goals. Enhancing your leadership skills could involve taking the lead on more ambitious projects or initiatives that require coordinating across teams. Let's focus on developing these leadership skills, including effective delegation, conflict resolution, and motivational techniques. We could start with leadership training sessions and mentorship from senior leaders to cultivate these qualities.",
  "In reviewing the criteria for promotion, it was noted that while your individual contributions are strong, there's an opportunity to improve in areas of innovation and creative problem-solving. Being at the forefront of our technological advancements requires not just following best practices but also pioneering new solutions. I encourage you to spearhead a 'skunkworks' project that tackles a problem we've not been able to solve yet. This could be a chance to demonstrate your innovative thinking and ability to drive change. Let’s discuss potential projects that excite you and align with our strategic goals."
]

NOT_HIGHER_DESIGNATION = [
  "I want to emphasize that achieving a 'meets expectations' rating is a testament to your solid performance, showcasing that you're meeting all the expectations set for your role. This includes [insert specific examples of accomplishments]. To aim for the 'exceeds expectations' rating in the future, we'd look for contributions such as [insert examples of what exceeding expectations might look like], which I believe is well within your reach.",
  "Receiving a 'meets expectations' designation means you've successfully fulfilled every requirement we've set, a feat that should not be underestimated. Your contributions, such as [insert examples], have been crucial. For the next level, 'exceeds expectations', we would be focusing on areas like [insert examples], and I'm here to support your growth towards that.",
  "Achieving a 'meets expectations' rating is a clear indication that you're performing exactly as needed in your current role, with achievements like [insert examples] standing out. To progress to 'exceeds expectations', it involves going beyond the core duties, perhaps by [insert examples], something I'm confident you can achieve with targeted effort.",
  "The 'meets expectations' rating signifies that you're fully meeting your role's requirements, including [insert examples of achievements], which is commendable. Advancing to the next level involves enhancing our impact by [insert examples of exceeding expectations], and I see great potential for you to make this step.",
  "Securing a 'meets expectations' rating reflects your commitment to your role, with accomplishments such as [insert examples] illustrating your valuable contribution. To elevate to an 'exceeds expectations' rating, we'd look to amplify your impact through initiatives like [insert examples], and I'm excited to see how you can exceed these expectations."
]

BAD_PERF = [
  "I want to be upfront about the 'does not meet expectations' rating. It reflects areas where we need to see improvement, such as [insert specific areas for improvement]. This is a critical moment for us to align on expectations and work together on a clear plan to address these gaps. Let's discuss how we can support your development and turn this around.",
  "Receiving a 'does not meet expectations' designation indicates that there are significant areas where your performance hasn't aligned with our expectations, including [insert examples]. This isn't easy news to share or receive, but it's important we tackle this head-on. We need to outline specific steps for improvement and how I can help you meet and eventually exceed expectations.",
  "This conversation is tough but necessary. Your performance has been rated as 'does not meet expectations', particularly in [insert areas needing improvement]. This signals that changes are needed in how we approach your work. Let's create a focused plan for your growth and how we can achieve the necessary improvements together.",
  "It's important to address the 'does not meet expectations' rating directly. It points to areas like [insert examples] that need immediate attention and improvement. While this is a challenging time, it's also an opportunity for significant growth. I'm committed to supporting you in making these adjustments and moving forward positively.",
  "The 'does not meet expectations' rating is a clear sign that we need to recalibrate and focus on [insert specific improvement areas]. It's crucial that we view this as a turning point. By setting clear goals and actionable steps for improvement, we can work together to get back on track. Let’s discuss a detailed plan for the next steps and how I can support you in this journey."
]

NO_SALARY_INCREASE = [
  "I understand that not receiving a salary increase this cycle might be disappointing. The decision is based on a variety of factors, including [insert general reasons like budget constraints, company performance]. Let's focus on your personal growth and set specific goals that can enhance your contributions and position you strongly for the next review cycle.",
  "Not getting a salary bump is tough, and I want to acknowledge your hard work and dedication. While salary adjustments are influenced by [insert reasons], it's important to look at how we can continue to grow your skills and impact. Let's map out a plan for your development and discuss opportunities for future compensation review.",
  "I know this news can be disheartening. The decision on salary adjustments takes into account many factors, and it’s not solely a reflection of your performance. I see this as an opportunity for us to identify key areas for your professional development and work towards ensuring your achievements are recognized in the next cycle.",
  "The absence of a salary increase this time around isn't easy, and I value your contributions greatly. Factors affecting this include [insert reasons]. This moment gives us a chance to realign on your career goals and how we can achieve them together, setting a clear path for future compensation adjustments.",
  "While a salary bump isn't happening this cycle, it's crucial we don't let this define our outlook. Your performance and potential are appreciated, and the decision involves factors beyond individual performance. Let's use this as a stepping stone to deepen your expertise and leadership, paving the way for future financial recognition."
]

SALARY_INCREASE_NOT_ENOUGH = [
  "I understand you were expecting a larger salary increase, and I want to acknowledge your feelings on this matter. The increase was determined by several factors, including [insert reasons like market standards, company performance, individual achievements]. Let's discuss how we can continue to build on your success and set goals for further growth and potential compensation adjustments.",
  "Hearing that the salary bump didn't meet your expectations is important feedback. While the increase reflects our appreciation for your work and the company's current capabilities, I'm here to support your career development and explore ways to enhance your future compensation in line with your contributions and growth.",
  "It's clear that the salary increase wasn't as you hoped, and it's crucial we talk about it. The adjustment was based on [insert rationale], aiming to balance fairness and recognition across the team. I value your contributions highly and believe there's room to grow. Let's plan for your continued development and discuss how this can be aligned with future compensation reviews.",
  "I recognize you're disappointed with the size of the salary increase. It's a reflection of several factors, not just your valuable contribution. As we move forward, I want to focus on identifying opportunities for your professional growth and setting objectives that could lead to more significant compensation changes in the future.",
  "Your feelings about the salary increase are completely understandable. This increase was guided by [insert factors], but this isn't the ceiling. Let's use this as motivation to focus on key areas for development and achievements that could influence future salary adjustments more substantially."
]

NO_BONUS = [
  "I understand that not receiving a bonus this year is disappointing. The decision around bonuses involves various factors, including [insert general reasons such as company performance, specific team goals, individual objectives]. Let’s discuss how we can align your efforts with the bonus criteria for the upcoming period and ensure your hard work is recognized.",
  "The absence of a bonus payment is certainly tough news to hear, especially given your contributions. While bonuses are influenced by [insert reasons], it's an opportunity for us to look at the broader picture of your career progression and how we can set targets for achievement and recognition in the future.",
  "Not getting a bonus this cycle is disappointing, and your feelings are valid. The allocation of bonuses is based on [insert reasons], which doesn't diminish the value of your work. Let's outline a plan focusing on key areas that align with our bonus criteria, aiming for a positive outcome in the next cycle.",
  "I know you were expecting a bonus, and it’s important to address why that hasn’t happened this time. Factors affecting bonus payments include [insert reasons]. This doesn’t take away from your contributions. Let’s work together on setting clear goals for the next review period, focusing on areas that can contribute to achieving a bonus.",
  "Learning that a bonus isn’t being awarded this year can be disheartening. It’s a complex decision that considers [insert reasons]. I appreciate your hard work and commitment. Moving forward, let’s identify specific goals and initiatives that can enhance your impact and position you for potential bonus eligibility in the future."
]

NO_REPEAT_BONUS = [
  "I recognize that not receiving a bonus this year, especially after receiving one last year, can be particularly disappointing. It's important to understand that bonus allocations change due to [insert reasons such as shifting company priorities, varying project outcomes, or performance benchmarks]. Let’s focus on how we can align your contributions with the evolving criteria to positively impact your bonus eligibility next year.",
  "Not getting a bonus this cycle, given you had one last year, understandably sets a different expectation. The factors influencing bonus payments include [insert reasons], which can vary year to year. I value your hard work and am committed to supporting you in aligning with the criteria for future bonus opportunities.",
  "Seeing a change in your bonus from last year to this year is disappointing, and I want to address any concerns you have. The decision is based on [insert reasons], reflecting broader changes within the company. Let's outline a plan to navigate these changes together and work towards meeting the bonus criteria going forward.",
  "The absence of a bonus this year, contrary to the last, might feel like a setback. It's crucial to look at [insert reasons] that led to this outcome. Your contributions are highly valued, and I believe there’s a clear path to aligning your efforts with the goals and expectations for a bonus in the future. Let's discuss how we can achieve this.",
  "I understand the frustration of not receiving a bonus after having one in the previous cycle. The criteria and conditions for bonus payments, including [insert reasons], can shift annually. This doesn't diminish your achievements or our appreciation for your work. Let's explore specific objectives and strategies to enhance your chances of receiving a bonus in the upcoming cycle."
]

NO_EQUITY = [
  "I understand that not receiving an equity refresher this cycle can be disappointing, especially considering your expectations and contributions. Equity decisions are influenced by [insert reasons such as company performance, specific achievement metrics, funding rounds]. Let’s discuss your career path and how we can align your performance with the equity criteria moving forward.",
  "The decision around equity refreshers involves a comprehensive review of many factors, including [insert reasons]. While I know this outcome isn’t what you were hoping for, I believe there’s a lot we can do to position you for future opportunities. Let’s focus on setting clear goals and identifying areas for impactful contributions.",
  "Not getting an equity refresher this time is tough news, and I want to acknowledge your hard work. The process for determining equity includes [insert reasons], and it’s important we understand how these apply. Let’s work together on a plan for the next review period, targeting key areas that could enhance your eligibility for equity in the future.",
  "I realize you were expecting an equity refresher, and not receiving one can be disheartening. It's a reflection of [insert reasons], which doesn't take away from the value you bring to the team. Moving forward, let’s identify specific objectives that align with the company’s goals and your personal growth, aiming for equity consideration in the next cycle.",
  "Learning that there won’t be an equity refresher for you in this cycle, especially after your dedication and contributions, is understandably disappointing. The criteria for equity awards include [insert reasons], which are subject to change. I’m here to support you in navigating these criteria and working towards a positive outcome in the future."
]
